version: "3"
services:
  ################################
  #   Setup React-admin container
  ################################
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.vite.dev
    container_name: a4_frontend
    env_file:
      - ./env/.env.dev
    environment:
      - NODE_ENV=development
      - REACT_APP_FACEBOOK_APPID=448400870781752
      - VITE_TITLE=Dockerization
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./uploads:/var/storage
    networks:
      - a4
  
  ################################
  #   Setup Api Graphql container
  ################################
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev   
    container_name: a4_backend          
    ports:
      - "4000:4000"
    env_file:
      - ./env/.env.dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # set can run docker inside ex. run docker backup db(a4_mongo)
      - ./backend/src:/app/src        
      - ./uploads:/app/uploads  
      - ./mongo/backups:/app/backups 
    networks:
      - a4
  ################################
networks:
  a4:
    external: true 