version: "3"
services:
  frontend:
    build: 
      context: ./frontend-webpack
      dockerfile: Dockerfile.prod
    container_name: insurance_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend-webpack/src:/app/src
      - ./uploads:/var/storage
    networks:
      - insurance-network
networks:
  insurance-network:
    external: true