version: "3"
services:
  ################################
  # Setup Insurance Frontend container
  ################################
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.vite.dev
    container_name: insurance_frontend
    env_file:
      - ./env/.env.ui
    environment:
      - NODE_ENV=development
      - REACT_APP_FACEBOOK_APPID=448400870781752
      - VITE_TITLE=Dockerization
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./uploads:/var/storage
    networks:
      - insurance-network
  ################################
  
networks:
  insurance-network:
    external: true 